feat: Refactor installation scripts for parallel execution and improved organization
- Updated applet installation script to download multiple applets in parallel, enhancing efficiency.
- Refactored cloning functions in various scripts to utilize parallel execution for faster repository cloning.
- Organized package installations into arrays for better readability and maintainability across different environments (Arch, Mac, Ubuntu, Work).
- Improved error handling for failed downloads and cloning operations, providing clearer feedback to the user.

diff --git a/.local/scripts/bootstrap/arch_functions b/.local/scripts/bootstrap/arch_functions
--- a/.local/scripts/bootstrap/arch_functions
+++ b/.local/scripts/bootstrap/arch_functions
@@ -172,13 +172,28 @@ base_install () {
 }
 
 git_repos() {
+    info "Cloning repos in parallel..."
     mkdir -p "$HOME/repos/"
     cd "$HOME/repos/" || exit
-    [ -d WinDotfiles ] || git clone https://github.com/cuberhaus/WinDotfiles.git
-    [ -d docs ]        || git clone https://github.com/cuberhaus/docs.git
-    [ -d dev ]         || git clone https://github.com/cuberhaus/dev.git
-    [ -d TFG ]         || git clone https://github.com/cuberhaus/TFG.git
-    [ -d fib ]         || git clone https://github.com/cuberhaus/fib.git
+    local pids=() names=()
+    local repos=(WinDotfiles docs dev TFG fib)
+    for name in "${repos[@]}"; do
+        if [ ! -d "$name" ]; then
+            git clone "https://github.com/cuberhaus/${name}.git" &
+            pids+=($!)
+            names+=("$name")
+        fi
+    done
+    local failures=0
+    for i in "${!pids[@]}"; do
+        if ! wait "${pids[$i]}"; then
+            warn "Failed to clone ${names[$i]}"
+            ((failures++)) || true
+        fi
+    done
+    if [ "$failures" -gt 0 ]; then
+        warn "$failures repo(s) failed to clone"
+    fi
 }
 
 arch_install() {
diff --git a/.local/scripts/bootstrap/ubuntu_functions b/.local/scripts/bootstrap/ubuntu_functions
--- a/.local/scripts/bootstrap/ubuntu_functions
+++ b/.local/scripts/bootstrap/ubuntu_functions
@@ -5,46 +5,49 @@ apt="sudo apt-get $flags install"
 ycm="$HOME/.local/scripts/ycm.sh" # make sure it's there
 scripts="$HOME/.local/scripts"
 
-base_install () { ## For windows install it's good to have this
-    # System tools
-    $apt autoconf 
-    $apt automake 
-    $apt bat                    # Better cat
-    $apt build-essential 
-    $apt cmake                  # To install ycm
-    $apt curl 
-    $apt eza                    # ls on steroids (exa replacement)
-    $apt file 
-    $apt fonts-powerline 
-    $apt fzf                    # Fuzzy finder
-    $apt git 
-    $apt gnome-shell 
-    $apt htop                   # Show system resources
-    $apt inkscape 
-    $apt laptop-detect
-    $apt libgtk-3-dev 
-    $apt ncdu                   # Manage storage
-    $apt neovim                 # Neovim
-    $apt nodejs
-    $apt npm 
-    $apt optipng 
-    $apt pkg-config 
-    $apt python3 
-    $apt python3-pip 
-    $apt ranger w3m             # Ranger
-    $apt rclone
-    $apt ruby-dev
-    $apt samba-common-bin 
-    $apt sassc 
-    $apt silversearcher-ag      # Better and faster ack (and grep)
-    $apt stow
-    $apt subversion             # To download repos
-    $apt tmux                   # Terminal multiplexer
-    $apt vim-gtk                # Vim with full functionality
-    $apt yarn 
-    $apt zsh
-    $apt eog                    # To view images, can launch it from terminal (works on windows)
-    $apt sshfs                  # To mount a remote file system with ssh (usefull to manipulate files with any ubuntu programs that you cannot install in remote) sshfs username@remote_host:/remote_directory ~/remote_dir
+base_install () {
+    local packages=(
+        autoconf
+        automake
+        bat                     # Better cat
+        build-essential
+        cmake                   # To install ycm
+        curl
+        eza                     # ls on steroids (exa replacement)
+        file
+        fonts-powerline
+        fzf                     # Fuzzy finder
+        git
+        gnome-shell
+        htop                    # Show system resources
+        inkscape
+        laptop-detect
+        libgtk-3-dev
+        ncdu                    # Manage storage
+        neovim
+        nodejs
+        npm
+        optipng
+        pkg-config
+        python3
+        python3-pip
+        ranger w3m              # Ranger and previews
+        rclone
+        ruby-dev
+        samba-common-bin
+        sassc
+        silversearcher-ag       # Better and faster ack (and grep)
+        stow
+        subversion              # To download repos
+        tmux                    # Terminal multiplexer
+        vim-gtk                 # Vim with full functionality
+        yarn
+        zsh
+        eog                     # Image viewer
+        sshfs                   # Mount remote filesystems over SSH
+    )
+    $apt "${packages[@]}"
+
     chsh -s "$(which zsh)"
     git config --global credential.helper store
 }
@@ -60,31 +63,28 @@ windows_install() {
 
 bloat_install () {
     brew install pipes-sh
-    $apt cmatrix
-    $apt cowsay                 # A cow displaying text
-    $apt fortune                # Random quotes
-    $apt neofetch 
+    $apt cmatrix cowsay fortune neofetch   # A cow, random quotes, system info
 }
 
 ubuntu_install() {
-    # GUI
-    $apt LXAppearance           # Theme
-    $apt arc-theme 
-    $apt audacity
-    $apt calibre
-    $apt cpu-checker qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
-    $apt gnome-screensaver      # Screensaver
-    $apt gparted                # Manage partitions
-    $apt pavucontrol            # Audio
-    $apt thunderbird            # Email
-    $apt timeshift              # Backups
-    $apt transmission           # A simpler Torrent D.
-    $apt vlc                    # Media player
-    $apt caffeine               # Prevent screen from going to sleep
-    $apt dconf-editor           # advanced configs
-
-    # Install Rstudio
-    $apt r-base
+    local packages=(
+        LXAppearance            # Theme
+        arc-theme
+        audacity
+        calibre
+        cpu-checker qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
+        gnome-screensaver       # Screensaver
+        gparted                 # Manage partitions
+        pavucontrol             # Audio
+        thunderbird             # Email
+        timeshift               # Backups
+        transmission            # A simpler Torrent client
+        vlc                     # Media player
+        caffeine                # Prevent screen from going to sleep
+        dconf-editor            # Advanced configs
+        r-base
+    )
+    $apt "${packages[@]}"
     if ! command -v rstudio &>/dev/null; then
         local rstudio_deb="/tmp/rstudio-latest-amd64.deb"
         wget -O "$rstudio_deb" https://rstudio.org/download/latest/daily/desktop/jammy/rstudio-latest-amd64.deb
@@ -159,32 +159,33 @@ emacs_install () {
 }
 
 i3_install () {
-    # Add repository and refresh apt
     sudo add-apt-repository -y ppa:kgilmer/speed-ricer
     sudo apt-get update
-    $apt i3-gaps
-    # Dependancies
-    $apt alsa-utils
-    $apt compton 
-    $apt conky 
-    $apt feh 
-    $apt flameshot 
-    $apt i3blocks 
-    $apt kitty 
-    $apt picom
-    $apt player-ctl 
-    $apt pulseaudio
-    $apt pulseaudio 
-    $apt pulseaudio-equalizer
-    $apt python-dbus 
-    $apt rofi 
-    $apt udiskie
-    $apt xbacklight
-    $apt xdotool
-    $apt xfce4-clipman
-    $apt xss-lock
-    $apt yad
-    $apt zenity
+
+    local packages=(
+        i3-gaps
+        alsa-utils
+        compton
+        conky
+        feh
+        flameshot
+        i3blocks
+        kitty
+        picom
+        player-ctl
+        pulseaudio
+        pulseaudio-equalizer
+        python-dbus
+        rofi
+        udiskie
+        xbacklight
+        xdotool
+        xfce4-clipman
+        xss-lock
+        yad
+        zenity
+    )
+    $apt "${packages[@]}"
 
     # Add current user to group video, type groups to see which groups you are in
     sudo usermod -a -G video "$LOGNAME"
@@ -325,21 +326,29 @@ optional() {
 }
 
 clone_repos() {
-    info "Cloning repos..."
+    info "Cloning repos in parallel..."
     mkdir -p "$HOME/repos"
-    local failures=0
     local repos=(
         "cuberhaus/WinDotfiles"
         "cuberhaus/dev"
         "cuberhaus/TFG"
         "cuberhaus/docs"
     )
+    local pids=() names=()
     for repo in "${repos[@]}"; do
         local name="${repo##*/}"
         if [ -d "$HOME/repos/$name" ]; then
             info "$name already exists, skipping"
-        elif ! git clone "https://github.com/$repo" "$HOME/repos/$name"; then
-            warn "Failed to clone $repo"
+        else
+            git clone "https://github.com/$repo" "$HOME/repos/$name" &
+            pids+=($!)
+            names+=("$repo")
+        fi
+    done
+    local failures=0
+    for i in "${!pids[@]}"; do
+        if ! wait "${pids[$i]}"; then
+            warn "Failed to clone ${names[$i]}"
             ((failures++)) || true
         fi
     done
